# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '4c8bfa3f5d6084ce7fc18797098b439f'
  config.secret_key = '1065521ae50c6f6a8ca6efd5d1ceeecf'
  config.default_from = 'emerih01@gmail.com'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
